getkoala/docs

admin-guides/advanced-instrumentation.mdx
admin-guides/advanced-intent-signals.mdx
admin-guides/how-to-drive-more-known-users.mdx
admin-guides/larger-sales-teams.mdx
get-started/how-koala-works.mdx
product-manual/audiences.mdx
product-manual/intent-signals.mdx
product-manual/koala-weekly.mdx
product-manual/slack-alerts.mdx
rep-guides/send-great-sales-messages.mdx
rep-guides/use-koala-for-research.mdx
tido-three-pillars.mdx

- added descriptions to product manual
- `e.g.,` per Grammarly
-  capitalize some Intent Signal / Slack Alert usage

add descriptions

---

developer-guides/server-side.mdx

This one skips bot fight mode.

use api2 in server-side docs

---

mint.json
sdk/autotracking.mdx
sdk/identify.mdx
sdk/installation.mdx
sdk/track.mdx

add some sdk docs

---

get-started/quick-start.mdx
sdk/installation.mdx

add csp troubleshooting to docs

---

admin-guides/advanced-instrumentation.mdx
sdk/identify.mdx

Add group id docs

---

get-started/identifying-users.mdx
sdk/identify.mdx

add docs about google/magic link/other sign in methods

---

developer-guides/custom-proxy-setup.mdx
mint.json

Based off of https://docs.google.com/document/d/1BS9phek_EF3w7d1NtRL_IlE-wmOD58aA32Wk1CVARoI/edit

add docs for custom proxy

---

developer-guides/install-on-nextjs.mdx
mint.json

add docs for nextjs

---

integrations/arcade.mdx
mint.json

add docs to capture Arcade events

---

integrations/calendly.mdx
mint.json

add basic docs for instrumenting calendly

---

integrations/salesforce.mdx

salesforce troubleshooting

---

get-started/quick-start.mdx

Add simple trouble shoot steps to help check the pixel installation

---

rep-guides/warm-outbound-minset.mdx

Updated video link warm-outbound-minset.mdx

---

integrations/g2.mdx

Add basic documentation for G2 integration

G2 documentation

---

integrations/hubspot.mdx
integrations/salesforce.mdx

Add docs for Account Scores Sync for both HubSpot and Salesforce

---

mint.json

switch "Sign up" to "Book a demo"

---

developer-guides/server-side.mdx

add docs about requirements for /batch

---

integrations/hubspot.mdx
integrations/salesforce.mdx

Update docs for score sync

---

product-manual/intent-scores.mdx

add docs for intent scores

---

get-started/quick-start.mdx
sdk/installation.mdx

add faq for custom namespaces for the sdk

---

automations/slack-alerts.mdx

https://linear.app/getkoala/issue/KOA-5186/404-link-on-docs

fix slack alerts link

---

developer-guides/server-side.mdx

add account events docs

---

automations/credits.mdx

Quinn aptly pointed out that this was outdated (and a little unclear). I tried to fix!

update docs for credits

---

integrations/hubspot.mdx
integrations/salesforce.mdx

---
Work-item-id: KOA-5796
Change-type: docs

Make it clear that account score sync are sent nightly

---

developer-guides/custom-proxy-setup.mdx

reference cloudflare in proxy docs
